###################
# WPI VMs
###################
horus
# 8 GB RAM, 8 cores, VM 500Gb storage
# CPU benchmark: ??? seconds # NOTE: Number of threads matters
melnibone 
# 8 GB RAM, 8 cores, VM
# mounts /research
# CPU benchmark: 9.43 seconds # NOTE: Number of threads matters
mournblade 
# 8 GB RAM, 8 cores, VM
# CPU benchmark: 9.90 seconds # NOTE: Number of threads matters
###################

###################
# Machines in Ph.D. lab
###################
rcp1 
# 128 GB RAM, 16 core, 32 thread, 2x Nvidia 4090
# CPU benchmark: 2.55 seconds # NOTE: Number of threads matters
# GPU benchmark: 0.69 seconds
rcp2 
# 128 GB RAM, 16 core, 32 thread, 2x Nvidia 4090
# CPU benchmark: 2.55 seconds # NOTE: Number of threads matters
# GPU benchmark: 0.69 seconds
rcp3 
# 512 GB RAM, 32 core, 64 thread, 2x Nvidia 4090
# CPU benchmark: 2.55 seconds # NOTE: Number of threads matters
# GPU benchmark: 0.69 seconds
##################

###################
# Mini computers
###################
beelink1 
# 32 GB RAM, 8 core, 16 thread
# CPU benchmark: ?? seconds # NOTE: Number of threads matters
beelink2
# 32 GB RAM, 8 core, 16 thread
# CPU benchmark: ?? seconds # NOTE: Number of threads matters
beelink3 
# 32 GB RAM, 8 core, 16 thread
# CPU benchmark: ?? seconds # NOTE: Number of threads matters
beelink4 
# 32 GB RAM, 8 core, 16 thread
# CPU benchmark: ?? seconds # NOTE: Number of threads matters
###################

###################
# The turing head node
###################
turing 
# 64 GB RAM, 16 core
# CPU benchmark: 2.92 seconds # NOTE: Number of threads matters

###################
# Desktop in my office in Ubuntu mode
###################
# abaddon
# 16 GB RAM, 12 core
# Nvidia 3060

###################
# The old laptop in my home office
###################
haven 
# 8 GB RAM, 8 core
# CPU benchmark: ??? seconds # NOTE: Number of threads matters
# avernus 
# 8 GB RAM, 8 core
# CPU benchmark: ??? seconds # NOTE: Number of threads matters


# For copying the SIF files
turing_with_python ansible_host=turing

###################
# Compute nodes on turing
###################
# Just for reference, here are some benchmarks
# Note, you can get different CPUs and GPUs on
# different nodes.
# CPU benchmark: 10.19 seconds # NOTE: Number of threads matters
# GPU benchmark: 1.41 seconds # NOTE: A100 GPU
compute1 ignore_unreachable=yes
compute2 ignore_unreachable=yes
compute3 ignore_unreachable=yes
compute4 ignore_unreachable=yes
compute5 ignore_unreachable=yes
compute6 ignore_unreachable=yes

# Mainly for benchmark
localhost ansible_connection=local 

# Note, the /usr/bin/python3 versus just python was changed because of a bug in 
# async_status: https://github.com/ansible/ansible/issues/43286

[all:vars]
NAME='2204'
BASE='22.04' 
ansible_python_interpreter=/usr/bin/python3

[wpi_root]
rcp1
rcp2
rcp3
beelink1
beelink2
beelink3
beelink4
horus
melnibone 
mournblade 

[wpi_hpc]
;This is here just for rcpaffenroth_setup.yml
turing

[personal]
# Haven is the laptop in my home office
haven

# The various service hosts
[service_host_gateway]
melnibone

[service_host_mongodb]
# More space than melnibone
beelink1

[service_host_rabbitmq]
# More space than melnibone
beelink1

[service_host_baserow]
# More space than melnibone
beelink1

[service_host_glance]
# More space than melnibone
beelink1

[service_host_beszel]
# More space than melnibone
beelink1

# the "children" makes this a group of groups
[have_rcpaffenroth:children]
personal
wpi_root
wpi_hpc

[have_root:children]
wpi_root
personal

[updatable:children]
wpi_root
personal

