localhost ansible_connection=local remote_tmp=/tmp #ansible_python_interpreter=/usr/bin/python3
# The default python interpreter on 22.04 does not have a recent openstacksdk module.  It has 0.61 when you
# need 1.0 for the newest ansible openstack module.  So, you need to use a different python interpreter
# for that one task.  This is the one I use for that.
# localhost ansible_python_interpreter=/home/rcpaffenroth/miniconda/bin/python
localhost ansible_python_interpreter=/usr/bin/python3

[all:vars]
NAME='2004'
BASE='20.04' 

[ansible_host]
localhost

[have_root]
localhost

[have_rcpaffenroth]
localhost

[docker_workspace]
localhost

[docker_workspace:vars]
image="base-ssh-{{ NAME }}"
